"""Export level metadata, the word bank and seed templates for the static (browser) build.

The TypeScript engine in ``frontend/src/engine`` reads ``data.json`` so level texts and
secrets stay defined in one place (here). ``tests/test_static_data.py`` fails if the
committed file drifts from the Python source.

    python -m scripts.export_static_data
"""

from __future__ import annotations

import json
from dataclasses import asdict
from pathlib import Path
from typing import Any

from app.levels import LEVELS
from app.wordbank import WORDS
from scripts.seed import DIRECT_REFS, INDIRECT_REFS, LEVEL_PREFS, TEMPLATES

OUT = Path(__file__).resolve().parents[2] / "frontend" / "src" / "engine" / "data.json"


def build() -> dict[str, Any]:
    return {
        "_comment": "Generated by backend/scripts/export_static_data.py - do not edit.",
        "levels": [
            {
                "id": s.id,
                "name": s.name,
                "guard_name": s.guard_name,
                "tagline": s.tagline,
                "defenses": list(s.defenses),
                "hint": s.hint,
                "explainer": asdict(s.explainer),
            }
            for s in LEVELS
        ],
        "words": [asdict(w) for w in WORDS],
        "seed": {
            "direct_refs": list(DIRECT_REFS),
            "indirect_refs": list(INDIRECT_REFS),
            "templates": [list(t) for t in TEMPLATES],
            "level_prefs": {str(k): v for k, v in LEVEL_PREFS.items()},
        },
    }


def render() -> str:
    return json.dumps(build(), indent=2, ensure_ascii=False) + "\n"


if __name__ == "__main__":
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(render(), encoding="utf-8")
    print(f"wrote {OUT}")
