import { useState } from "react";
import {
  Area,
  AreaChart,
  Bar,
  BarChart,
  CartesianGrid,
  Legend,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from "recharts";
import { api, STATIC } from "../api/client";
import type { Outcome } from "../api/types";
import { Heatmap } from "../components/Heatmap";
import { DownloadIcon } from "../components/Icons";
import { StatCard } from "../components/StatCard";
import { Toggle } from "../components/Toggle";
import { useAsync } from "../hooks/useAsync";
import { layerLabel, OUTCOME_META, pct, techniqueLabel } from "../lib/format";

const axis = { stroke: "#3a3a3c", fontSize: 11, fontFamily: "-apple-system, BlinkMacSystemFont, sans-serif" };
const tooltipStyle = {
  contentStyle: {
    background: "#161618",
    border: "1px solid rgba(255, 255, 255, 0.1)",
    borderRadius: 12,
    fontFamily: "-apple-system, BlinkMacSystemFont, sans-serif",
    fontSize: 12,
  },
  labelStyle: { color: "#f5f5f7" },
};
const LAYER_COLORS = ["#2997ff", "#5e5ce6", "#64d2ff", "#30d158", "#ff9f0a", "#ff453a", "#bf5af2"];
const OUTCOMES: Outcome[] = ["blocked", "rate_limited", "refused", "partial_leak", "leaked"];

export function Dashboard() {
  const [includeSynthetic, setIncludeSynthetic] = useState(true);
  const { data, error, loading } = useAsync(() => api.research(includeSynthetic), [includeSynthetic]);

  if (error) return <p className="text-alert-400">Failed to load: {error.message}</p>;
  if (!data) return <p className="text-ink-400">{loading ? "Loading…" : ""}</p>;

  const { totals } = data;
  const synthetic = totals.synthetic_attempts;
  const levelChart = data.levels.map((l) => ({
    name: `L${l.level}`,
    "Solve rate": l.solve_rate,
    "Info-leak rate": l.bypass_rate,
    "Raw model leak rate": l.model_leak_rate,
  }));
  const caughtChart = data.levels.map((l) => ({ name: `L${l.level}`, ...l.caught_by }));
  const techniqueChart = Object.entries(data.technique_counts)
    .sort((a, b) => b[1] - a[1])
    .map(([t, n]) => ({ name: techniqueLabel(t), attempts: n }));

  return (
    <div className="space-y-6">
      <header className="flex flex-wrap items-end justify-between gap-4">
        <div>
          <p className="text-xs font-medium uppercase tracking-[0.1em] text-neutral-400">Research Dashboard</p>
          <h1 className="mt-1 text-3xl font-semibold tracking-tight text-white">What gets through, and what stops it</h1>
        </div>
        <div className="flex items-center gap-4">
          <Toggle checked={includeSynthetic} onChange={setIncludeSynthetic} label="include synthetic data" />
          <a
            className="btn-ghost"
            href={STATIC ? "#" : api.exportUrl(includeSynthetic)}
            download="gauntlet-attacks.jsonl"
            onClick={async (e) => {
              if (!STATIC) return;
              e.preventDefault();
              const text = await api.exportJsonl(includeSynthetic);
              const url = URL.createObjectURL(new Blob([text], { type: "application/x-ndjson" }));
              const a = document.createElement("a");
              a.href = url;
              a.download = "gauntlet-attacks.jsonl";
              a.click();
              URL.revokeObjectURL(url);
            }}
          >
            <DownloadIcon width={15} height={15} /> Export JSONL
          </a>
        </div>
      </header>

      {synthetic > 0 && (
        <div className="rounded-xl border border-white/[0.08] bg-white/[0.03] px-4 py-3 text-xs text-neutral-300">
          <strong className="font-medium text-white">Synthetic data:</strong> {synthetic.toLocaleString()} of{" "}
          {totals.attempts.toLocaleString()} attempts were generated by <code>scripts/seed.py</code>{" "}
          (simulated attacks vs. offline mock guard) to illustrate the analytics pipeline.
        </div>
      )}

      <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <StatCard label="attempts logged" value={totals.attempts.toLocaleString()} />
        <StatCard label="players" value={totals.sessions} />
        <StatCard label="levels cleared" value={totals.solves} accent="text-white" />
        <StatCard
          label="info-leak rate"
          value={pct(totals.bypass_rate)}
          sub="replies delivered with full or partial secret"
          accent="text-cyan-glow"
        />
      </section>

      <section className="grid gap-4 lg:grid-cols-2">
        <div className="panel p-5">
          <p className="panel-title mb-4">per-level rates</p>
          <ResponsiveContainer width="100%" height={260}>
            <BarChart data={levelChart} barGap={4}>
              <CartesianGrid stroke="#222226" vertical={false} />
              <XAxis dataKey="name" {...axis} />
              <YAxis {...axis} tickFormatter={(v: number) => pct(v)} domain={[0, 1]} />
              <Tooltip {...tooltipStyle} formatter={(v) => pct(Number(v), 1)} cursor={{ fill: "#1c1c1e" }} />
              <Legend wrapperStyle={{ fontSize: 11, fontFamily: "-apple-system, BlinkMacSystemFont, sans-serif" }} />
              <Bar dataKey="Solve rate" fill="#f5f5f7" radius={[4, 4, 0, 0]} isAnimationActive={false} />
              <Bar dataKey="Info-leak rate" fill="#2997ff" radius={[4, 4, 0, 0]} isAnimationActive={false} />
              <Bar dataKey="Raw model leak rate" fill="#8e8e93" radius={[4, 4, 0, 0]} isAnimationActive={false} />
            </BarChart>
          </ResponsiveContainer>
          <p className="mt-2 text-xs text-ink-400">
            Raw model leak = the guard model produced the secret before output-side defenses ran.
          </p>
        </div>
        <div className="panel p-5">
          <p className="panel-title mb-4">which layer caught attacks</p>
          <ResponsiveContainer width="100%" height={260}>
            <BarChart data={caughtChart}>
              <CartesianGrid stroke="#1b2432" vertical={false} />
              <XAxis dataKey="name" {...axis} />
              <YAxis {...axis} />
              <Tooltip {...tooltipStyle} cursor={{ fill: "#121924" }} />
              <Legend
                wrapperStyle={{ fontSize: 11, fontFamily: "JetBrains Mono" }}
                formatter={(v: string) => layerLabel(v)}
              />
              {data.layers.map((layer, i) => (
                <Bar
                  key={layer}
                  dataKey={layer}
                  name={layer}
                  stackId="a"
                  fill={LAYER_COLORS[i % LAYER_COLORS.length]}
                  isAnimationActive={false}
                />
              ))}
            </BarChart>
          </ResponsiveContainer>
        </div>
      </section>

      <section className="panel p-5">
        <p className="panel-title mb-1">technique × defense heatmap</p>
        <p className="mb-4 text-xs text-ink-400">
          Share of attempts using each technique that got full or partial information out, per level.
        </p>
        <Heatmap cells={data.heatmap} techniques={data.techniques} levels={data.levels.map((l) => l.level)} />
      </section>

      <section className="grid gap-4 lg:grid-cols-[1.4fr_1fr]">
        <div className="panel p-5">
          <p className="panel-title mb-4">attempts over time</p>
          <ResponsiveContainer width="100%" height={260}>
            <AreaChart data={data.timeseries}>
              <CartesianGrid stroke="#1b2432" vertical={false} />
              <XAxis dataKey="date" {...axis} tickFormatter={(d: string) => d.slice(5)} />
              <YAxis {...axis} />
              <Tooltip {...tooltipStyle} />
              <Legend wrapperStyle={{ fontSize: 11, fontFamily: "JetBrains Mono" }} />
              {OUTCOMES.map((o) => (
                <Area
                  key={o}
                  type="monotone"
                  dataKey={o}
                  name={OUTCOME_META[o].label}
                  stackId="1"
                  stroke={OUTCOME_META[o].color}
                  fill={OUTCOME_META[o].color}
                  fillOpacity={0.25}
                  isAnimationActive={false}
                />
              ))}
            </AreaChart>
          </ResponsiveContainer>
        </div>
        <div className="panel p-5">
          <p className="panel-title mb-4">technique frequency</p>
          <ResponsiveContainer width="100%" height={260}>
            <BarChart data={techniqueChart} layout="vertical" margin={{ left: 8 }}>
              <XAxis type="number" {...axis} />
              <YAxis type="category" dataKey="name" {...axis} fontSize={10} width={120} interval={0} />
              <Tooltip {...tooltipStyle} cursor={{ fill: "#121924" }} />
              <Bar dataKey="attempts" fill="#a78bfa" radius={[0, 3, 3, 0]} isAnimationActive={false} />
            </BarChart>
          </ResponsiveContainer>
        </div>
      </section>
    </div>
  );
}
